---

- name: Install Netdata agent
  hosts: all
  remote_user: "{{ansible_user}}"
  gather_facts: true
  become: true

  roles:
    - { role: install_netdata_repository, become: true }
    - { role: install_netdata_agent, become: true }
