---

- name: Install Netdata agent
  hosts: all
  remote_user: "{{ansible_user}}"
  gather_facts: true
  become: true

  pre_tasks:

    - name: Add EPEL repository for Centos/Rocky
      ansible.builtin.package:
        name: epel-release
        state: latest
        #      when: ansible_facts['os_family'] == 'RedHat'
      when:
        ansible_distribution in ['RedHat', 'CentOS', 'ScientificLinux'] and
        (ansible_distribution_version is version_compare('7', '<') or
        ansible_distribution_version is version_compare('8', '>='))

  roles:
    - { role: install_netdata_repository, become: true }
    - { role: install_netdata_agent, become: true }
