- name: Purge netdata agent and netdata agent repository
  hosts: all
  gather_facts: true
  become: true

  roles:
    - { role: purge-netdata-agent, become: true }
    - { role: purge-netdata-repository, become: true }
