- name: Apply the netdata.conf.j2 template
  template:
    src: netdata.conf.j2
    dest: "{{ netdata_config_dir }}/netdata.conf"
    owner: root
    group: root
    mode: '0644'
  notify: Restart Netdata
