---

# Suse

- name: Add repo and install package
  block:

    - name: Add netfilter repository configuration for Suse
      community.general.zypper_repository:
        repo: "https://download.opensuse.org/repositories/security:netfilter/openSUSE_Tumbleweed/security:netfilter.repo"
        state: present
        auto_import_keys: true

    - name: Install dependencies
      community.general.zypper:
        name: libnetfilter_acct1
        state: present

    - name: Import Netdata GPG key
      ansible.builtin.rpm_key:
        state: present
        key: https://repository.netdata.cloud/netdatabot.gpg.key

    - name: Add repository for Suse
      community.general.zypper_repository:
        name: "netdata"
        repo: 'https://repository.netdata.cloud/repos/stable/opensuse/$releasever/$basearch'
        state: present
        auto_import_keys: true

    - name: Add repository configuration for Suse
      community.general.zypper_repository:
        name: "netdata-repoconfig"
        repo: 'https://repository.netdata.cloud/repos/stable/opensuse/$releasever/$basearch'
        state: present
        auto_import_keys: true

    - name: Install package on Suse
      community.general.zypper:
        name: netdata
        state: present
      notify: Restart Netdata

    - name: Install chart support on Suse if enabled
      community.general.zypper:
        name: netdata-plugin-chartsd
        state: present
      notify: Restart Netdata
      when: netdata_manage_charts
