---

- name: Gather facts
  ansible.builtin.setup:

- name: Install the Netdata Linux agent on Debian
  ansible.builtin.include_tasks: install-debian.yml
  when: "'debian' in ansible_facts.distribution | lower"

- name: Install the Netdata Linux agent on Ubuntu
  ansible.builtin.include_tasks: install-ubuntu.yml
  when: "'ubuntu' in ansible_facts.distribution | lower"

- name: Install the Netdata Linux agent on OpenSUSE
  ansible.builtin.include_tasks: install-opensuse.yml
  when: "'opensuse' in ansible_facts.distribution | lower"

- name: Configure the Netdata Linux agent
  ansible.builtin.include_tasks: configure-linux.yml
  when: netdata_manage_config and ansible_facts.os_family != "Windows" and ansible_facts.os_family != "Darwin"

- name: Claim node if claim_token
  ansible.builtin.include_tasks: node_claim.yml
  when: netdata_claim
