---
# tasks file for roles/claim

- name: Get information about running agent
  ansible.builtin.command: netdatacli aclk-state json
  register: agent_info

  # - set_fact:
  #  is_online: "{{ agent_info.stdout | from_json | json_query('online') }}"

- name: Set fact for is_claimed
  ansible.builtin.set_fact:
    is_claimed: "{{ agent_info.stdout | from_json | json_query('\"agent-claimed\"') }}"

- name: Claim the new node if is not claimed yet
  block:
    - name: Generate UUID
      ansible.builtin.command: uuidgen
      register: uuid

    - name: Set fact new_uuid
      ansible.builtin.set_fact:
        new_uuid: "{{ uuid.stdout }}"

    - name: Claim the node
      ansible.builtin.command: netdata-claim.sh -token="{{ claim_token }}" -rooms="{{ claim_rooms }}" -url="{{ claim_url }}" -id="{{ new_uuid }}"
      notify: restart netdata agent

  when: not is_claimed
