---
dependency:
  name: galaxy

driver:
  name: docker

platforms:

  - name: Debian10
    image: debian:10
    pre_build_image: false
    dockerfile: ../common/Dockerfile_debian10.j2

  - name: debian11
    image: debian:11
    pre_build_image: false
    dockerfile: ../common/Dockerfile_debian11.j2

  - name: centos7
    image: quay.io/centos/centos:7
    pre_build_image: true

  - name: fedora35
    image: fedora:35
    pre_build_image: true

  - name: ubuntu2204
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    dockerfile: ../common/Dockerfile_ubuntu2204.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: false

  - name: oraclelinux8
    image: oraclelinux:8
    pre_build_image: true

  - name: rockylinux8
    image: rockylinux:8
    pre_build_image: true


provisioner:
  name: ansible
  env:
    MOLECULE_NO_LOG: false

verifier:
  name: ansible
