---

- name: Remove Netdata packages
  ansible.builtin.yum:
    state: absent
    name: netdata

- name: Remove the remains
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/netdata
    - /var/log/netdata
    - /var/lib/netdata
    - /var/cache/netdata
    - /usr/libexec/netdata
