name: Container Test

on:
  push:
  pull_request:

jobs:

  debian-test-job:
    runs-on: ubuntu-latest
    # Test installation against Ubuntu 24.04
    container:
      image: debian:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test installation
        run: |
          apt-get -y update; apt-get -y upgrade; apt-get -y install ansible
          ansible-playbook tests/test.yml

  ubuntu-test-job:
    runs-on: ubuntu-latest
    # Test installation against Ubuntu 24.04
    container:
      image: ubuntu:24
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test installation
        run: |
          apt-get -y update; apt-get -y upgrade; apt-get -y install ansible
          ansible-playbook tests/test.yml
