name: Container Test

on:
  push:
  pull_request:

jobs:
  test:
    name: Test installation against Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: |
          sudo apt-get update; sudo apt-get upgrade
          sudo apt-get install ansible
          ansible-playbook tests/test.yml
